baseURL: "https://byrgeleeuwangh.com/"
title: Byrge Leeuwangh
paginate: 8
theme: hugo-PaperMod
enableInlineShortcodes: true
enableRobotsTXT: true
enableGitInfo: true

# googleAnalytics: UA-123-45

minify:
    disableXML: true
    # minifyOutput: true

outputs:
  home:
      - HTML
      - RSS
      - JSON

permalinks:
  posts: /:title/

languages:
    en:
        languageName: "English"
        weight: 1
        menu:
            main:
                - name: Tags
                  url: tags/
                  weight: 5
                - name: Search
                  url: search/
                  weight: 10
                - name: About me
                  url: about-me/
                  weight: 15
                - name: Archive
                  url: archives
                  weight: 20

    # l2:
    #     languageName: "Lang2"
    #     weight: 2
    #     title: PaperModL2
    #     profileMode:
    #         enabled: true
    #         title: PaperMod
            # imageUrl: "#"
            # imageTitle: my image
            # imageWidth: 120
            # imageHeight: 120
    #         subtitle: "☄️ Fast | ☁️ Fluent | 🌙 Smooth | 📱 Responsive"
    #         buttons:
    #             - name: Blog
    #               url: posts
    #             - name: Tags
    #               url: tags
    #     menu:
    #         main:
    #             - name: Archive
    #               url: archives/
    #               weight: 5
    #             - name: Tags
    #               url: tags
    #               weight: 10
    #             - name: Categories
    #               url: categories
    #               weight: 10
    #             - name: Series
    #               url: series
    #               weight: 10
    #             - name: NullLink
    #               url: "#"
    #             - name: NullLink2
    #               url: "#"
    #             - name: NullLink3
    #               url: "#"

    # l3:
    #     languageName: "Langrtl"
    #     languagedirection: rtl
    #     weight: 3
    #     title: PaperMod RTL
    #     homeInfoParams:
    #         Title: "Hi there \U0001F44B"
    #         Content: Welcome to RTL layout
    #     menu:
    #         main:
    #             - name: Tags
    #               url: tags
    #               weight: 10

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production
    description: "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
    GitSourceUrl: "https://github.com/byrge/hugo_byrgeleeuwangh"
    author: Byrge Leeuwangh
    # author: ["Me", "You"] # multiple authors
    ShowReadingTime: true
    defaultTheme: auto
    ShowShareButtons: true
    displayFullLangName: true
    # images: ""
    # assets:
    #   favicon: '<path / external url>'

    profileMode:
        enabled: false
        title: PaperMod
        imageUrl: "#"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Archives
              url: archives
            - name: Tags
              url: tags

    homeInfoParams:
        Title: "Hi there \U0001F44B"
        Content: >
            Welcome to my blog.

            - I'm **Byrge Leeuwangh** and working as a Technical Web Analyst in The Netherlands.

    socialIcons:
        - name: twitter
          url: "https://twitter.com/leeuwangh"
        # - name: stackoverflow
        #   url: "#"
        - name: codepen
          url: "#"
        - name: linkedin
          url: "https://www.linkedin.com/in/byrgeleeuwangh/"
        - name: github
          url: "https://github.com/byrge/hugo_byrgeleeuwangh"

taxonomies:
    category: categories
    tag: tags
    series: series

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
